swagger: "2.0"
info:
  description: "Esta es la descripción de las peticiones ralizadas en el microservicio: Crear Pregunta Nueva"
  version: "1.0.0"
  title: "Geosmart - MS Crear pregunta nueva"
host: "3.92.114.227"
tags:
- name: "mNewQ"
  description: "Ruta base para realiar las peticiones del microservicio"
  
schemes:
- "http"
paths:
  /mNewQ:
    post:
      tags:
      - "mNewQ"
      summary: "Crear pregunta nueva"
      description: "Petición para crear una pregunta nueva"
      operationId: "createQ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Esquema con los datos de la pregunta"
        required: true
        schema:
          $ref: '#/definitions/Question'
      responses:
        "405":
          description: "Invalid input"
    
  /mNewQ/{questionId}:
    get:
      tags:
      - "mNewQ"
      summary: "Retornar pregunta mediante ID"
      description: "Petición para leer una pregunta y retornarla"
      operationId: "readQ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "questionId"
        in: "path"
        description: "ID de pregunta"
        required: true
        type: "integer"
        format: "int64"

      responses:
        "400":
          description: "Invalid id supplied"
        
    put:
      tags:
      - "mNewQ"
      summary: "Actualizar pregunta mediante ID"
      description: "Petición para actualizar una pregunta"
      operationId: "updateQ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "questionId"
        in: "path"
        description: "ID de pregunta"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Esquema con los datos de la pregunta"
        required: true
        schema:
          $ref: "#/definitions/Question"
      responses:
        "400":
          description: "Invalid id supplied"
          
    delete:
      tags:
      - "mNewQ"
      summary: "Eliminar pregunta"
      description: "Eliminar pregunta mediante ID"
      operationId: "deleteQ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "questionId"
        in: "path"
        description: "ID de pregunta"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "Category not found"      
   
  /mNewQ/getAll:
    get:
      tags:
      - "mNewQ"
      summary: "Retornar toda la colección de preguntas"
      description: "Petición para leer y obtener todas las preguntas"
      operationId: "getQ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input" 
          
definitions:
 
  Question:
    type: "object"
    properties:
      id: 
        type: "integer"
        format: "int64"
      title: 
        type: "string"
        description: ""
      questionCategory: 
        type: "string"
        description: ""
      question: 
        type: "string"
        description: ""  
      optionA: 
        type: "string"
        description: ""
      optionB: 
        type: "string"
        description: ""
      optionC: 
        type: "string"
        description: ""
      optionD: 
        type: "string"
        description: ""
      answer: 
        type: "string"
        description: ""
      created_ad: 
        type: "string"
        format: "date-time"
        description: ""  
      updated_at: 
        type: "string"
        format: "date-time"
        description: ""
      created_by: 
        type: "string"
        description: ""
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"